name: proof-jobs
apps:
- name: web
  source_dir: /
  github:
    repo: Ajalways/MYJOBBOARD
    branch: main
  build_command: npm run build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 5000
  envs:
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    value: file:./prisma/dev.db