name: proof-jobs
apps:
- name: web
  source_dir: /
  github:
    repo: Ajalways/MYJOBBOARD
    branch: main
  build_command: cd src && npm ci && npm run build
  run_command: cd src && npm run start:deploy
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: DATABASE_URL
    value: file:./prisma/dev.db